remote_theme: artemsheludko/flexible-jekyll
title: Matt's Technical Blog
description: I'm Matt, an App Modernization Consultant specializing in solutions centered around Azure and GitHub.  I decided that it was time to get into blogging, so here I am!  
permalink: '/:title'
baseurl: '/'
url: 'https://molson504x.github.io'

# Author Settings
author: Matt Olson
author-img: me.jpg
about-author: I'm an App Modernization Consultant for <a href="http://www.xpirit.com">Xpirit</a> specializing in Azure and GitHub solutions.
#social-twitter: 
#social-facebook: 
social-github: molson504x 
#social-linkedin: 
social-email: molson@xpirit.com

# Build Settings
#markdown: kramdown
plugins:
  - jekyll-remote-theme
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"